name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore dependencies
      run: dotnet restore 
      working-directory: './Copilot.MAUI'

    - name: Build
      run: dotnet build  --no-restore
      working-directory: './Copilot.MAUI'

    - name: Test
      run: dotnet test --no-build
      working-directory: './Copilot.MAUI'

